import '../models/api_models.dart';
import '../models/song_stats.dart';

/// Remaps stale song IDs in playlists and stats by matching on
/// title, artist, and (for playlists) duration.
///
/// This solves the problem where moving the music library to a different
/// folder changes all file paths, which in turn changes the MD5-based
/// song IDs generated by the server.
class SongIdRemappingService {
  static final SongIdRemappingService _instance =
      SongIdRemappingService._internal();
  factory SongIdRemappingService() => _instance;
  SongIdRemappingService._internal();

  static const int _durationToleranceSeconds = 3;

  /// Remap stale song IDs in playlists using current library data.
  /// Preserves IDs that still exist in the library.
  List<PlaylistModel> remapPlaylists(
    List<PlaylistModel> playlists,
    List<SongModel> librarySongs,
  ) {
    if (librarySongs.isEmpty) return playlists;

    final index = _SongLookupIndex(librarySongs);
    final librarySongsById = {for (final s in librarySongs) s.id: s};

    return playlists
        .map((p) => _remapPlaylist(p, index, librarySongsById))
        .toList();
  }

  PlaylistModel _remapPlaylist(
    PlaylistModel playlist,
    _SongLookupIndex index,
    Map<String, SongModel> librarySongsById,
  ) {
    final newSongIds = <String>[];
    final newSongAlbumIds = <String, String>{};
    final newSongTitles = <String, String>{};
    final newSongArtists = <String, String>{};
    final newSongDurations = <String, int>{};
    var anyIdChanged = false;

    for (final oldId in playlist.songIds) {
      // If the ID is still valid in the current library, keep it.
      final existingSong = librarySongsById[oldId];
      if (existingSong != null) {
        newSongIds.add(oldId);
        if (existingSong.albumId != null) {
          newSongAlbumIds[oldId] = existingSong.albumId!;
        }
        newSongTitles[oldId] = existingSong.title;
        newSongArtists[oldId] = existingSong.artist;
        newSongDurations[oldId] = existingSong.duration;
        continue;
      }

      // Stale ID — try to find a match by metadata.
      final oldTitle = playlist.songTitles[oldId] ?? '';
      final oldArtist = playlist.songArtists[oldId] ?? '';
      final oldDuration = playlist.songDurations[oldId] ?? 0;

      final newId = index.findMatch(oldTitle, oldArtist, oldDuration);
      if (newId != null) {
        anyIdChanged = true;
        final matchedSong = librarySongsById[newId]!;
        newSongIds.add(newId);
        if (matchedSong.albumId != null) {
          newSongAlbumIds[newId] = matchedSong.albumId!;
        }
        newSongTitles[newId] = matchedSong.title;
        newSongArtists[newId] = matchedSong.artist;
        newSongDurations[newId] = matchedSong.duration;
      } else {
        // No match found — preserve the original entry so the user sees
        // "Unknown Song" rather than having the track silently removed.
        newSongIds.add(oldId);
        if (playlist.songAlbumIds.containsKey(oldId)) {
          newSongAlbumIds[oldId] = playlist.songAlbumIds[oldId]!;
        }
        if (playlist.songTitles.containsKey(oldId)) {
          newSongTitles[oldId] = playlist.songTitles[oldId]!;
        }
        if (playlist.songArtists.containsKey(oldId)) {
          newSongArtists[oldId] = playlist.songArtists[oldId]!;
        }
        if (playlist.songDurations.containsKey(oldId)) {
          newSongDurations[oldId] = playlist.songDurations[oldId]!;
        }
      }
    }

    if (!anyIdChanged) return playlist;

    return playlist.copyWith(
      songIds: newSongIds,
      songAlbumIds: newSongAlbumIds,
      songTitles: newSongTitles,
      songArtists: newSongArtists,
      songDurations: newSongDurations,
      modifiedAt: DateTime.now(),
    );
  }

  /// Remap stale song IDs in stats using current library data.
  /// Stats do not store per-song duration, so matching falls back to
  /// title + artist only.
  ///
  /// When multiple input stats resolve to the same songId after remapping
  /// (for example, a stale entry from a prior library move co-existing with
  /// a fresh entry for the same song, or two stale entries collapsing onto
  /// one library song), they are merged: play counts and total time are
  /// summed, the earliest [SongStats.firstPlayed] and latest
  /// [SongStats.lastPlayed] are kept. This is essential because aggregations
  /// like top-artists/top-albums sum every per-song row and would otherwise
  /// double-count plays whenever the database has duplicate rows for the
  /// same physical song under different ids.
  List<SongStats> remapStats(
    List<SongStats> stats,
    List<SongModel> librarySongs,
  ) {
    if (librarySongs.isEmpty) return stats;

    final index = _SongLookupIndex(librarySongs);
    final librarySongsById = {for (final s in librarySongs) s.id: s};

    final remapped = stats.map((stat) {
      // If the ID is still valid, keep it.
      if (librarySongsById.containsKey(stat.songId)) {
        return stat;
      }

      final newId = index.findMatch(
        stat.songTitle ?? '',
        stat.songArtist ?? '',
        0, // No duration available for stats.
      );

      if (newId != null) {
        final matchedSong = librarySongsById[newId]!;
        return stat.copyWith(
          songId: newId,
          songTitle: matchedSong.title,
          songArtist: matchedSong.artist,
          albumId: matchedSong.albumId,
        );
      }

      return stat;
    }).toList();

    return _mergeDuplicateStatsBySongId(remapped);
  }

  /// Merge entries that share a songId. Returns the original list reference
  /// when no duplicates are present, so callers can detect a no-op.
  List<SongStats> _mergeDuplicateStatsBySongId(List<SongStats> stats) {
    if (stats.length <= 1) return stats;

    final seen = <String>{};
    var hasDuplicate = false;
    for (final stat in stats) {
      if (!seen.add(stat.songId)) {
        hasDuplicate = true;
        break;
      }
    }
    if (!hasDuplicate) return stats;

    final mergedById = <String, SongStats>{};
    for (final stat in stats) {
      final existing = mergedById[stat.songId];
      mergedById[stat.songId] =
          existing == null ? stat : _mergeStats(existing, stat);
    }
    return mergedById.values.toList();
  }

  static SongStats _mergeStats(SongStats a, SongStats b) {
    return SongStats(
      songId: a.songId,
      playCount: a.playCount + b.playCount,
      totalTime: Duration(
        seconds: a.totalTime.inSeconds + b.totalTime.inSeconds,
      ),
      firstPlayed: _earlierDate(a.firstPlayed, b.firstPlayed),
      lastPlayed: _laterDate(a.lastPlayed, b.lastPlayed),
      songTitle: a.songTitle ?? b.songTitle,
      songArtist: a.songArtist ?? b.songArtist,
      albumId: a.albumId ?? b.albumId,
      album: a.album ?? b.album,
      albumArtist: a.albumArtist ?? b.albumArtist,
    );
  }

  static DateTime? _earlierDate(DateTime? a, DateTime? b) {
    if (a == null) return b;
    if (b == null) return a;
    return a.isBefore(b) ? a : b;
  }

  static DateTime? _laterDate(DateTime? a, DateTime? b) {
    if (a == null) return b;
    if (b == null) return a;
    return a.isAfter(b) ? a : b;
  }
}

class _SongLookupIndex {
  final Map<String, List<SongModel>> _byTitleArtist = {};

  _SongLookupIndex(List<SongModel> songs) {
    for (final song in songs) {
      final key = '${_normalize(song.title)}|||${_normalize(song.artist)}';
      _byTitleArtist.putIfAbsent(key, () => []).add(song);
    }
  }

  String? findMatch(String title, String artist, int duration) {
    final key = '${_normalize(title)}|||${_normalize(artist)}';
    final candidates = _byTitleArtist[key];
    if (candidates == null || candidates.isEmpty) return null;
    if (candidates.length == 1) return candidates.first.id;

    // Multiple candidates — use duration tolerance to disambiguate.
    for (final candidate in candidates) {
      if ((candidate.duration - duration).abs() <=
          SongIdRemappingService._durationToleranceSeconds) {
        return candidate.id;
      }
    }

    // No duration match; fall back to the first candidate.
    return candidates.first.id;
  }

  static String _normalize(String s) {
    return s.toLowerCase().trim();
  }
}
