/// Models for cross-client listening statistics.
///
/// Listening activity is captured as immutable client-generated events with
/// stable [ListeningEvent.eventId]s. The server deduplicates by eventId, so a
/// client may retry an upload forever without double-counting. Rollups
/// ([ListeningSongRollup]) are derived server-side from the raw event log and
/// can always be rebuilt from it.
library;

/// A single listening event generated by a playback client.
///
/// Two shapes are used in practice:
/// - Time segments: `listenedMs > 0, plays == 0` — actual seconds of forward
///   audio-position progress (scrubbing never inflates this).
/// - Play markers: `plays == 1, listenedMs == 0` — emitted once per
///   play-action ([playId]) when the play threshold (30s or 50% of the track,
///   whichever is smaller) is reached.
///
/// A one-time baseline import of a device's pre-existing local stats uses
/// `plays >= 0, listenedMs >= 0` in one event with a deterministic eventId so
/// re-imports are idempotent.
class ListeningEvent {
  final String eventId;
  final String songId;

  /// Groups the events of one play-action (one continuous listen of a track,
  /// including pause/resume). Repeat-one wraps start a new playId. Used by the
  /// server as a second line of defence against double-counted plays.
  final String? playId;

  /// Milliseconds of genuine listening credited by this event.
  final int listenedMs;

  /// Number of plays credited by this event (0 or 1, except baseline imports).
  final int plays;

  /// Client wall-clock time the event was finalized (UTC epoch ms).
  final int occurredAtMs;

  /// The client's UTC offset in minutes at [occurredAtMs], so per-day rollups
  /// can be grouped by the listener's local day.
  final int tzOffsetMinutes;

  // Denormalized display metadata so stats survive library changes.
  final String? songTitle;
  final String? songArtist;
  final String? albumId;
  final String? album;
  final String? albumArtist;

  /// Song duration in ms if known; lets the server sanity-cap segments.
  final int? songDurationMs;

  const ListeningEvent({
    required this.eventId,
    required this.songId,
    this.playId,
    required this.listenedMs,
    required this.plays,
    required this.occurredAtMs,
    required this.tzOffsetMinutes,
    this.songTitle,
    this.songArtist,
    this.albumId,
    this.album,
    this.albumArtist,
    this.songDurationMs,
  });

  Map<String, dynamic> toJson() => <String, dynamic>{
        'eventId': eventId,
        'songId': songId,
        if (playId != null) 'playId': playId,
        'listenedMs': listenedMs,
        'plays': plays,
        'occurredAtMs': occurredAtMs,
        'tzOffsetMinutes': tzOffsetMinutes,
        if (songTitle != null) 'songTitle': songTitle,
        if (songArtist != null) 'songArtist': songArtist,
        if (albumId != null) 'albumId': albumId,
        if (album != null) 'album': album,
        if (albumArtist != null) 'albumArtist': albumArtist,
        if (songDurationMs != null) 'songDurationMs': songDurationMs,
      };

  /// Tolerant parser; returns null when required fields are missing/invalid
  /// rather than throwing, so one malformed event can't fail a whole batch.
  static ListeningEvent? tryFromJson(Map<String, dynamic> json) {
    final eventId = json['eventId'];
    final songId = json['songId'];
    if (eventId is! String || eventId.isEmpty) return null;
    if (songId is! String || songId.isEmpty) return null;
    final listenedMs = json['listenedMs'];
    final plays = json['plays'];
    final occurredAtMs = json['occurredAtMs'];
    final tzOffsetMinutes = json['tzOffsetMinutes'];
    final songDurationMs = json['songDurationMs'];
    return ListeningEvent(
      eventId: eventId,
      songId: songId,
      playId: json['playId'] is String ? json['playId'] as String : null,
      listenedMs: listenedMs is num ? listenedMs.toInt() : 0,
      plays: plays is num ? plays.toInt() : 0,
      occurredAtMs: occurredAtMs is num
          ? occurredAtMs.toInt()
          : DateTime.now().toUtc().millisecondsSinceEpoch,
      tzOffsetMinutes: tzOffsetMinutes is num ? tzOffsetMinutes.toInt() : 0,
      songTitle:
          json['songTitle'] is String ? json['songTitle'] as String : null,
      songArtist:
          json['songArtist'] is String ? json['songArtist'] as String : null,
      albumId: json['albumId'] is String ? json['albumId'] as String : null,
      album: json['album'] is String ? json['album'] as String : null,
      albumArtist:
          json['albumArtist'] is String ? json['albumArtist'] as String : null,
      songDurationMs: songDurationMs is num ? songDurationMs.toInt() : null,
    );
  }
}

/// Per-user per-song aggregate derived from the event log.
class ListeningSongRollup {
  final String songId;
  final int playCount;
  final int listenedMs;
  final int? firstPlayedMs;
  final int? lastPlayedMs;
  final String? songTitle;
  final String? songArtist;
  final String? albumId;
  final String? album;
  final String? albumArtist;

  const ListeningSongRollup({
    required this.songId,
    required this.playCount,
    required this.listenedMs,
    this.firstPlayedMs,
    this.lastPlayedMs,
    this.songTitle,
    this.songArtist,
    this.albumId,
    this.album,
    this.albumArtist,
  });

  Map<String, dynamic> toJson() => <String, dynamic>{
        'songId': songId,
        'playCount': playCount,
        'listenedMs': listenedMs,
        if (firstPlayedMs != null) 'firstPlayedMs': firstPlayedMs,
        if (lastPlayedMs != null) 'lastPlayedMs': lastPlayedMs,
        if (songTitle != null) 'songTitle': songTitle,
        if (songArtist != null) 'songArtist': songArtist,
        if (albumId != null) 'albumId': albumId,
        if (album != null) 'album': album,
        if (albumArtist != null) 'albumArtist': albumArtist,
      };

  factory ListeningSongRollup.fromJson(Map<String, dynamic> json) {
    return ListeningSongRollup(
      songId: json['songId'] as String? ?? '',
      playCount: (json['playCount'] as num?)?.toInt() ?? 0,
      listenedMs: (json['listenedMs'] as num?)?.toInt() ?? 0,
      firstPlayedMs: (json['firstPlayedMs'] as num?)?.toInt(),
      lastPlayedMs: (json['lastPlayedMs'] as num?)?.toInt(),
      songTitle: json['songTitle'] as String?,
      songArtist: json['songArtist'] as String?,
      albumId: json['albumId'] as String?,
      album: json['album'] as String?,
      albumArtist: json['albumArtist'] as String?,
    );
  }
}

/// The account-wide stats summary served to clients.
class ListeningStatsSummary {
  final List<ListeningSongRollup> songs;
  final int totalListenedMs;
  final int totalPlays;
  final int generatedAtMs;

  const ListeningStatsSummary({
    required this.songs,
    required this.totalListenedMs,
    required this.totalPlays,
    required this.generatedAtMs,
  });

  Map<String, dynamic> toJson() => <String, dynamic>{
        'songs': songs.map((s) => s.toJson()).toList(),
        'totalListenedMs': totalListenedMs,
        'totalPlays': totalPlays,
        'generatedAtMs': generatedAtMs,
      };

  factory ListeningStatsSummary.fromJson(Map<String, dynamic> json) {
    final songs = (json['songs'] as List<dynamic>? ?? const <dynamic>[])
        .whereType<Map<String, dynamic>>()
        .map(ListeningSongRollup.fromJson)
        .where((rollup) => rollup.songId.isNotEmpty)
        .toList();
    return ListeningStatsSummary(
      songs: songs,
      totalListenedMs: (json['totalListenedMs'] as num?)?.toInt() ?? 0,
      totalPlays: (json['totalPlays'] as num?)?.toInt() ?? 0,
      generatedAtMs: (json['generatedAtMs'] as num?)?.toInt() ?? 0,
    );
  }

  static const ListeningStatsSummary empty = ListeningStatsSummary(
    songs: <ListeningSongRollup>[],
    totalListenedMs: 0,
    totalPlays: 0,
    generatedAtMs: 0,
  );
}
