/// Models for cross-client listening statistics.
///
/// Listening activity is captured as immutable client-generated events with
/// stable [ListeningEvent.eventId]s. The server deduplicates by eventId, so a
/// client may retry an upload forever without double-counting. Rollups
/// ([ListeningSongRollup]) are derived server-side from the raw event log and
/// can always be rebuilt from it.
library;

/// A single listening event generated by a playback client.
///
/// Two shapes are used in practice:
/// - Time segments: `listenedMs > 0, plays == 0` — actual seconds of forward
///   audio-position progress (scrubbing never inflates this).
/// - Play markers: `plays == 1, listenedMs == 0` — emitted once per
///   play-action ([playId]) when the play threshold (30s or 50% of the track,
///   whichever is smaller) is reached.
///
/// A one-time baseline import of a device's pre-existing local stats uses
/// `plays >= 0, listenedMs >= 0` in one event with a deterministic eventId so
/// re-imports are idempotent.
class ListeningEvent {
  final String eventId;
  final String songId;

  /// Groups the events of one play-action (one continuous listen of a track,
  /// including pause/resume). Repeat-one wraps start a new playId. Used by the
  /// server as a second line of defence against double-counted plays.
  final String? playId;

  /// Milliseconds of genuine listening credited by this event.
  final int listenedMs;

  /// Number of plays credited by this event (0 or 1, except baseline imports).
  final int plays;

  /// Client wall-clock time the event was finalized (UTC epoch ms).
  final int occurredAtMs;

  /// The client's UTC offset in minutes at [occurredAtMs], so per-day rollups
  /// can be grouped by the listener's local day.
  final int tzOffsetMinutes;

  // Denormalized display metadata so stats survive library changes.
  final String? songTitle;
  final String? songArtist;
  final String? albumId;
  final String? album;
  final String? albumArtist;

  /// Song duration in ms if known; lets the server sanity-cap segments.
  final int? songDurationMs;

  // Optional playback context (additive; old clients simply omit these and
  // old servers ignore them).

  /// Where playback was started from: 'album', 'playlist', 'search',
  /// 'queue', 'download', ...
  final String? sourceKind;

  /// The playlist the play-action started from, when [sourceKind] is
  /// 'playlist'.
  final String? playlistId;

  /// The reporting client class: 'mobile', 'desktop' or 'tv'.
  final String? clientKind;

  const ListeningEvent({
    required this.eventId,
    required this.songId,
    this.playId,
    required this.listenedMs,
    required this.plays,
    required this.occurredAtMs,
    required this.tzOffsetMinutes,
    this.songTitle,
    this.songArtist,
    this.albumId,
    this.album,
    this.albumArtist,
    this.songDurationMs,
    this.sourceKind,
    this.playlistId,
    this.clientKind,
  });

  ListeningEvent withAlbumMetadata({
    String? albumId,
    String? album,
    String? albumArtist,
  }) {
    return ListeningEvent(
      eventId: eventId,
      songId: songId,
      playId: playId,
      listenedMs: listenedMs,
      plays: plays,
      occurredAtMs: occurredAtMs,
      tzOffsetMinutes: tzOffsetMinutes,
      songTitle: songTitle,
      songArtist: songArtist,
      albumId: albumId ?? this.albumId,
      album: album ?? this.album,
      albumArtist: albumArtist ?? this.albumArtist,
      songDurationMs: songDurationMs,
      sourceKind: sourceKind,
      playlistId: playlistId,
      clientKind: clientKind,
    );
  }

  Map<String, dynamic> toJson() => <String, dynamic>{
        'eventId': eventId,
        'songId': songId,
        if (playId != null) 'playId': playId,
        'listenedMs': listenedMs,
        'plays': plays,
        'occurredAtMs': occurredAtMs,
        'tzOffsetMinutes': tzOffsetMinutes,
        if (songTitle != null) 'songTitle': songTitle,
        if (songArtist != null) 'songArtist': songArtist,
        if (albumId != null) 'albumId': albumId,
        if (album != null) 'album': album,
        if (albumArtist != null) 'albumArtist': albumArtist,
        if (songDurationMs != null) 'songDurationMs': songDurationMs,
        if (sourceKind != null) 'sourceKind': sourceKind,
        if (playlistId != null) 'playlistId': playlistId,
        if (clientKind != null) 'clientKind': clientKind,
      };

  /// Tolerant parser; returns null when required fields are missing/invalid
  /// rather than throwing, so one malformed event can't fail a whole batch.
  static ListeningEvent? tryFromJson(Map<String, dynamic> json) {
    final eventId = json['eventId'];
    final songId = json['songId'];
    if (eventId is! String || eventId.isEmpty) return null;
    if (songId is! String || songId.isEmpty) return null;
    final listenedMs = json['listenedMs'];
    final plays = json['plays'];
    final occurredAtMs = json['occurredAtMs'];
    final tzOffsetMinutes = json['tzOffsetMinutes'];
    final songDurationMs = json['songDurationMs'];
    return ListeningEvent(
      eventId: eventId,
      songId: songId,
      playId: json['playId'] is String ? json['playId'] as String : null,
      listenedMs: listenedMs is num ? listenedMs.toInt() : 0,
      plays: plays is num ? plays.toInt() : 0,
      occurredAtMs: occurredAtMs is num
          ? occurredAtMs.toInt()
          : DateTime.now().toUtc().millisecondsSinceEpoch,
      tzOffsetMinutes: tzOffsetMinutes is num ? tzOffsetMinutes.toInt() : 0,
      songTitle:
          json['songTitle'] is String ? json['songTitle'] as String : null,
      songArtist:
          json['songArtist'] is String ? json['songArtist'] as String : null,
      albumId: json['albumId'] is String ? json['albumId'] as String : null,
      album: json['album'] is String ? json['album'] as String : null,
      albumArtist:
          json['albumArtist'] is String ? json['albumArtist'] as String : null,
      songDurationMs: songDurationMs is num ? songDurationMs.toInt() : null,
      sourceKind:
          json['sourceKind'] is String ? json['sourceKind'] as String : null,
      playlistId:
          json['playlistId'] is String ? json['playlistId'] as String : null,
      clientKind:
          json['clientKind'] is String ? json['clientKind'] as String : null,
    );
  }
}

/// Per-user per-song aggregate derived from the event log.
class ListeningSongRollup {
  final String songId;
  final int playCount;
  final int listenedMs;
  final int? firstPlayedMs;
  final int? lastPlayedMs;
  final String? songTitle;
  final String? songArtist;
  final String? albumId;
  final String? album;
  final String? albumArtist;

  const ListeningSongRollup({
    required this.songId,
    required this.playCount,
    required this.listenedMs,
    this.firstPlayedMs,
    this.lastPlayedMs,
    this.songTitle,
    this.songArtist,
    this.albumId,
    this.album,
    this.albumArtist,
  });

  Map<String, dynamic> toJson() => <String, dynamic>{
        'songId': songId,
        'playCount': playCount,
        'listenedMs': listenedMs,
        if (firstPlayedMs != null) 'firstPlayedMs': firstPlayedMs,
        if (lastPlayedMs != null) 'lastPlayedMs': lastPlayedMs,
        if (songTitle != null) 'songTitle': songTitle,
        if (songArtist != null) 'songArtist': songArtist,
        if (albumId != null) 'albumId': albumId,
        if (album != null) 'album': album,
        if (albumArtist != null) 'albumArtist': albumArtist,
      };

  factory ListeningSongRollup.fromJson(Map<String, dynamic> json) {
    return ListeningSongRollup(
      songId: json['songId'] as String? ?? '',
      playCount: (json['playCount'] as num?)?.toInt() ?? 0,
      listenedMs: (json['listenedMs'] as num?)?.toInt() ?? 0,
      firstPlayedMs: (json['firstPlayedMs'] as num?)?.toInt(),
      lastPlayedMs: (json['lastPlayedMs'] as num?)?.toInt(),
      songTitle: json['songTitle'] as String?,
      songArtist: json['songArtist'] as String?,
      albumId: json['albumId'] as String?,
      album: json['album'] as String?,
      albumArtist: json['albumArtist'] as String?,
    );
  }
}

/// The account-wide stats summary served to clients.
class ListeningStatsSummary {
  final List<ListeningSongRollup> songs;
  final int totalListenedMs;
  final int totalPlays;
  final int generatedAtMs;

  /// Whether the account holds any Spotify-imported listening events.
  /// Additive wire field: old clients ignore it, old servers omit it.
  final bool hasSpotifyImport;

  /// Distinct local days on which the account listened to anything (the
  /// `total` day grain, so baseline imports are excluded but real imported
  /// history counts). Clients divide lifetime playtime by this for a
  /// "per active day" average that a single stray timestamp can't distort.
  /// Additive wire field: 0 from old servers, where clients fall back to the
  /// first-to-last calendar span.
  final int activeDays;

  const ListeningStatsSummary({
    required this.songs,
    required this.totalListenedMs,
    required this.totalPlays,
    required this.generatedAtMs,
    this.hasSpotifyImport = false,
    this.activeDays = 0,
  });

  Map<String, dynamic> toJson() => <String, dynamic>{
        'songs': songs.map((s) => s.toJson()).toList(),
        'totalListenedMs': totalListenedMs,
        'totalPlays': totalPlays,
        'generatedAtMs': generatedAtMs,
        'hasSpotifyImport': hasSpotifyImport,
        'activeDays': activeDays,
      };

  factory ListeningStatsSummary.fromJson(Map<String, dynamic> json) {
    final songs = (json['songs'] as List<dynamic>? ?? const <dynamic>[])
        .whereType<Map<String, dynamic>>()
        .map(ListeningSongRollup.fromJson)
        .where((rollup) => rollup.songId.isNotEmpty)
        .toList();
    return ListeningStatsSummary(
      songs: songs,
      totalListenedMs: (json['totalListenedMs'] as num?)?.toInt() ?? 0,
      totalPlays: (json['totalPlays'] as num?)?.toInt() ?? 0,
      generatedAtMs: (json['generatedAtMs'] as num?)?.toInt() ?? 0,
      // Strictly the JSON literal true; missing/null/wrong type stay false.
      hasSpotifyImport: json['hasSpotifyImport'] == true,
      // Tolerant: any non-numeric (missing/null/wrong type) becomes 0, which
      // makes clients fall back to the calendar-span average rather than throw.
      activeDays: json['activeDays'] is num
          ? (json['activeDays'] as num).toInt()
          : 0,
    );
  }

  static const ListeningStatsSummary empty = ListeningStatsSummary(
    songs: <ListeningSongRollup>[],
    totalListenedMs: 0,
    totalPlays: 0,
    generatedAtMs: 0,
  );
}

/// Per-user aggregate for one credited artist, derived from the event log by
/// splitting raw artist strings server-side (see CreditedArtistSplitter).
/// Every credited artist on a song receives the full play and full listened
/// time — credit is never divided between collaborators.
class ListeningArtistRollup {
  /// Normalized grouping key; stable across casing/whitespace variants.
  final String artistKey;

  /// Best display label (original casing preserved).
  final String? artistDisplay;

  final int playCount;
  final int listenedMs;
  final int? firstPlayedMs;
  final int? lastPlayedMs;

  const ListeningArtistRollup({
    required this.artistKey,
    this.artistDisplay,
    required this.playCount,
    required this.listenedMs,
    this.firstPlayedMs,
    this.lastPlayedMs,
  });

  Map<String, dynamic> toJson() => <String, dynamic>{
        'artistKey': artistKey,
        if (artistDisplay != null) 'artistDisplay': artistDisplay,
        'playCount': playCount,
        'listenedMs': listenedMs,
        if (firstPlayedMs != null) 'firstPlayedMs': firstPlayedMs,
        if (lastPlayedMs != null) 'lastPlayedMs': lastPlayedMs,
      };

  factory ListeningArtistRollup.fromJson(Map<String, dynamic> json) {
    return ListeningArtistRollup(
      artistKey: json['artistKey'] as String? ?? '',
      artistDisplay: json['artistDisplay'] as String?,
      playCount: (json['playCount'] as num?)?.toInt() ?? 0,
      listenedMs: (json['listenedMs'] as num?)?.toInt() ?? 0,
      firstPlayedMs: (json['firstPlayedMs'] as num?)?.toInt(),
      lastPlayedMs: (json['lastPlayedMs'] as num?)?.toInt(),
    );
  }
}

/// Per-user aggregate for one album, derived from the event log.
class ListeningAlbumRollup {
  /// Grouping key: the album id when the event carried one, otherwise a
  /// normalized-name key so untagged libraries still group sensibly.
  final String albumKey;

  /// The catalog album id, when known.
  final String? albumId;

  final String? album;
  final String? albumArtist;
  final int playCount;
  final int listenedMs;
  final int? firstPlayedMs;
  final int? lastPlayedMs;

  const ListeningAlbumRollup({
    required this.albumKey,
    this.albumId,
    this.album,
    this.albumArtist,
    required this.playCount,
    required this.listenedMs,
    this.firstPlayedMs,
    this.lastPlayedMs,
  });

  Map<String, dynamic> toJson() => <String, dynamic>{
        'albumKey': albumKey,
        if (albumId != null) 'albumId': albumId,
        if (album != null) 'album': album,
        if (albumArtist != null) 'albumArtist': albumArtist,
        'playCount': playCount,
        'listenedMs': listenedMs,
        if (firstPlayedMs != null) 'firstPlayedMs': firstPlayedMs,
        if (lastPlayedMs != null) 'lastPlayedMs': lastPlayedMs,
      };

  factory ListeningAlbumRollup.fromJson(Map<String, dynamic> json) {
    return ListeningAlbumRollup(
      albumKey: json['albumKey'] as String? ?? '',
      albumId: json['albumId'] as String?,
      album: json['album'] as String?,
      albumArtist: json['albumArtist'] as String?,
      playCount: (json['playCount'] as num?)?.toInt() ?? 0,
      listenedMs: (json['listenedMs'] as num?)?.toInt() ?? 0,
      firstPlayedMs: (json['firstPlayedMs'] as num?)?.toInt(),
      lastPlayedMs: (json['lastPlayedMs'] as num?)?.toInt(),
    );
  }
}

/// Plays + listened time credited to one local day.
class ListeningDailyTotal {
  final int playCount;
  final int listenedMs;

  const ListeningDailyTotal({
    required this.playCount,
    required this.listenedMs,
  });

  Map<String, dynamic> toJson() => <String, dynamic>{
        'playCount': playCount,
        'listenedMs': listenedMs,
      };

  factory ListeningDailyTotal.fromJson(Map<String, dynamic> json) {
    return ListeningDailyTotal(
      playCount: (json['playCount'] as num?)?.toInt() ?? 0,
      listenedMs: (json['listenedMs'] as num?)?.toInt() ?? 0,
    );
  }
}

/// Aggregated stats for an arbitrary local-day range (a single day, a month,
/// a year, ...). Derived from the daily rollups, so months/years are range
/// queries over day rows rather than separate tables. Baseline imports never
/// contribute (they compress years of history into one timestamp).
class ListeningPeriodStats {
  /// Inclusive local-day bounds, `yyyy-mm-dd`.
  final String fromDay;
  final String toDay;

  final int totalPlays;
  final int totalListenedMs;
  final List<ListeningSongRollup> songs;
  final List<ListeningArtistRollup> artists;
  final List<ListeningAlbumRollup> albums;

  /// Per-day totals within the range, keyed by local day.
  final Map<String, ListeningDailyTotal> days;

  const ListeningPeriodStats({
    required this.fromDay,
    required this.toDay,
    required this.totalPlays,
    required this.totalListenedMs,
    required this.songs,
    required this.artists,
    required this.albums,
    required this.days,
  });

  Map<String, dynamic> toJson() => <String, dynamic>{
        'from': fromDay,
        'to': toDay,
        'totalPlays': totalPlays,
        'totalListenedMs': totalListenedMs,
        'songs': songs.map((s) => s.toJson()).toList(),
        'artists': artists.map((a) => a.toJson()).toList(),
        'albums': albums.map((a) => a.toJson()).toList(),
        'days': days.map((day, total) => MapEntry(day, total.toJson())),
      };

  factory ListeningPeriodStats.fromJson(Map<String, dynamic> json) {
    final days = <String, ListeningDailyTotal>{};
    final rawDays = json['days'];
    if (rawDays is Map<String, dynamic>) {
      for (final entry in rawDays.entries) {
        final value = entry.value;
        if (value is Map<String, dynamic>) {
          days[entry.key] = ListeningDailyTotal.fromJson(value);
        }
      }
    }
    return ListeningPeriodStats(
      fromDay: json['from'] as String? ?? '',
      toDay: json['to'] as String? ?? '',
      totalPlays: (json['totalPlays'] as num?)?.toInt() ?? 0,
      totalListenedMs: (json['totalListenedMs'] as num?)?.toInt() ?? 0,
      songs: (json['songs'] as List<dynamic>? ?? const <dynamic>[])
          .whereType<Map<String, dynamic>>()
          .map(ListeningSongRollup.fromJson)
          .where((rollup) => rollup.songId.isNotEmpty)
          .toList(),
      artists: (json['artists'] as List<dynamic>? ?? const <dynamic>[])
          .whereType<Map<String, dynamic>>()
          .map(ListeningArtistRollup.fromJson)
          .where((rollup) => rollup.artistKey.isNotEmpty)
          .toList(),
      albums: (json['albums'] as List<dynamic>? ?? const <dynamic>[])
          .whereType<Map<String, dynamic>>()
          .map(ListeningAlbumRollup.fromJson)
          .where((rollup) => rollup.albumKey.isNotEmpty)
          .toList(),
      days: days,
    );
  }
}
